namespace CybersecurityApp
{
    partial class ChatControl
    {
        // Partial class generated by the Windows Forms Designer
        private System.ComponentModel.IContainer components = null; // Container for designer-managed components

        protected override void Dispose(bool disposing)
        {
            // Disposes of resources, including components, if managed
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            // Initializes chat interface components
            this.chatDisplayTextBox = new System.Windows.Forms.TextBox();
            this.inputTextBox = new System.Windows.Forms.TextBox();
            this.chatDisplayTextBox.Location = new System.Drawing.Point(10, 10);
            this.chatDisplayTextBox.Multiline = true;
            this.chatDisplayTextBox.Size = new System.Drawing.Size(750, 350);
            this.inputTextBox.Location = new System.Drawing.Point(10, 370);
            this.inputTextBox.Size = new System.Drawing.Size(750, 20);
            this.Controls.Add(this.chatDisplayTextBox);
            this.Controls.Add(this.inputTextBox);
            this.Name = "ChatControl";
            this.Size = new System.Drawing.Size(770, 400);
        }

        private System.Windows.Forms.TextBox chatDisplayTextBox; // Displays chat history
        private System.Windows.Forms.TextBox inputTextBox; // Accepts user input
    }
}