namespace CybersecurityApp
{
    partial class LogControl
    {
        // Partial class generated by the Windows Forms Designer
        private System.ComponentModel.IContainer components = null; // Container for designer-managed components

        protected override void Dispose(bool disposing)
        {
            // Disposes of resources, including components, if managed
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            // Initializes log interface components
            this.logListBox = new System.Windows.Forms.ListBox();
            this.logListBox.Location = new System.Drawing.Point(10, 10);
            this.logListBox.Name = "logListBox";
            this.logListBox.Size = new System.Drawing.Size(750, 400);
            this.logListBox.TabIndex = 0;
            this.Controls.Add(this.logListBox);
            this.Name = "LogControl";
            this.Size = new System.Drawing.Size(770, 450);
        }

        private System.Windows.Forms.ListBox logListBox; // Displays the list of log entries
    }
}