namespace CybersecurityApp
{
    partial class MainForm
    {
        // Partial class generated by the Windows Forms Designer
        private System.ComponentModel.IContainer components = null; // Container for designer-managed components

        protected override void Dispose(bool disposing)
        {
            // Disposes of resources, including components, if managed
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            // Initializes all components defined in the designer (e.g., tabControl, tabs)
            this.tabControl = new System.Windows.Forms.TabControl();
            this.tabChat = new System.Windows.Forms.TabPage();
            this.tabTasks = new System.Windows.Forms.TabPage();
            this.tabQuiz = new System.Windows.Forms.TabPage();
            this.tabLog = new System.Windows.Forms.TabPage();
            this.tabControl.Controls.Add(this.tabChat);
            this.tabControl.Controls.Add(this.tabTasks);
            this.tabControl.Controls.Add(this.tabQuiz);
            this.tabControl.Controls.Add(this.tabLog);
            this.Controls.Add(this.tabControl);
            // Sets up layout and properties for all controls
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Name = "MainForm";
            this.Text = "Cybersecurity Awareness App";
        }

        private System.Windows.Forms.TabControl tabControl; // Main tab control for navigation
        private System.Windows.Forms.TabPage tabChat; // Tab for chat functionality
        private System.Windows.Forms.TabPage tabTasks; // Tab for task management
        private System.Windows.Forms.TabPage tabQuiz; // Tab for quiz questions
        private System.Windows.Forms.TabPage tabLog; // Tab for activity logging
    }
}