namespace CybersecurityApp
{
    partial class QuizControl
    {
        // Partial class generated by the Windows Forms Designer
        private System.ComponentModel.IContainer components = null; // Container for designer-managed components

        protected override void Dispose(bool disposing)
        {
            // Disposes of resources, including components, if managed
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            // Initializes quiz interface components
            this.questionLabel = new System.Windows.Forms.Label();
            this.answerComboBox = new System.Windows.Forms.ComboBox();
            this.submitButton = new System.Windows.Forms.Button();
            this.scoreLabel = new System.Windows.Forms.Label();
            // Sets up layout and properties for all controls
            this.Controls.Add(this.questionLabel);
            this.Controls.Add(this.answerComboBox);
            this.Controls.Add(this.submitButton);
            this.Controls.Add(this.scoreLabel);
            this.Name = "QuizControl";
            this.Size = new System.Drawing.Size(770, 400);
        }

        private System.Windows.Forms.Label questionLabel; // Displays the current question
        private System.Windows.Forms.ComboBox answerComboBox; // Dropdown for answer options
        private System.Windows.Forms.Button submitButton; // Button to submit answers
        private System.Windows.Forms.Label scoreLabel; // Displays the quiz score
    }
}