namespace CybersecurityApp
{
    partial class TaskControl
    {
        // Partial class generated by the Windows Forms Designer
        private System.ComponentModel.IContainer components = null; // Container for designer-managed components

        protected override void Dispose(bool disposing)
        {
            // Disposes of resources, including components, if managed
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            // Initializes task management interface components
            this.taskListBox = new System.Windows.Forms.ListBox();
            this.taskTitleTextBox = new System.Windows.Forms.TextBox();
            this.taskDescriptionTextBox = new System.Windows.Forms.TextBox();
            this.taskReminderDateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.addTaskButton = new System.Windows.Forms.Button();
            this.completeTaskButton = new System.Windows.Forms.Button();
            this.deleteTaskButton = new System.Windows.Forms.Button();
            // Sets up layout and properties for all controls
            this.Controls.Add(this.taskListBox);
            this.Controls.Add(this.taskTitleTextBox);
            this.Controls.Add(this.taskDescriptionTextBox);
            this.Controls.Add(this.taskReminderDateTimePicker);
            this.Controls.Add(this.addTaskButton);
            this.Controls.Add(this.completeTaskButton);
            this.Controls.Add(this.deleteTaskButton);
            this.Name = "TaskControl";
            this.Size = new System.Drawing.Size(770, 400);
        }

        private System.Windows.Forms.ListBox taskListBox; // Displays task list
        private System.Windows.Forms.TextBox taskTitleTextBox; // Input for task title
        private System.Windows.Forms.TextBox taskDescriptionTextBox; // Input for task description
        private System.Windows.Forms.DateTimePicker taskReminderDateTimePicker; // Input for task reminder
        private System.Windows.Forms.Button addTaskButton; // Button to add tasks
        private System.Windows.Forms.Button completeTaskButton; // Button to mark tasks as complete
        private System.Windows.Forms.Button deleteTaskButton; // Button to delete tasks
    }
}